import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const base = process.argv[2] ?? 'http://127.0.0.1:8787';
const request = (path, init = {}) => fetch(base + path, {...init, signal:AbortSignal.timeout(30000)});
const health = await request('/healthz');
assert.equal(health.status, 200);
const res = await request('/v1/dns?name=example.com&type=A');
assert.equal(res.status, 402);
const encoded = res.headers.get('payment-required');
assert.ok(encoded);
const challenge = JSON.parse(Buffer.from(encoded,'base64').toString());
assert.equal(challenge.accepts[0].network, 'eip155:2368');
assert.equal(challenge.accepts[0].amount, '1000000000000000');
assert.equal((await request('/v1/dns?name=example.com/path')).status,400);
assert.equal((await request('/v1/dns?name=example.com',{method:'POST'})).status,405);
assert.equal((await request('/V1/DNS/?name=example.com')).status,402);
assert.equal((await request('/v1/not-a-route')).status,404);
await writeFile(new URL('../evidence/workers-unpaid-smoke.json',import.meta.url),JSON.stringify({recorded_at:new Date().toISOString(),base,checks:['health 200','unpaid 402','Kite testnet challenge','invalid URL 400','POST 405','route alias 402','unknown route 404'],challenge,on_chain_payment_performed:false},null,2)+'\n');
console.log('PASS: Workers HTTP smoke checks; no payment performed.');
